gui:
  nerdFontsVersion: "3"
git:
  overrideGpg: true
  pagers:
    - pager: delta --paging=never --line-numbers
keybinding:
  universal:
    nextBlock-alt2: <disabled>
    prevBlock-alt2: <disabled>
    nextTab: '<tab>'
    prevTab: '<backtab>'
    pushFiles: <disabled>
  branches:
    forceCheckoutBranch: <disabled>

customCommands:
  - key: 'P'
    description: 'Push options...'
    command: 'git push {{.Form.Flags}}'
    context: 'global'
    prompts:
      - type: 'menu'
        title: 'Push options...'
        key: 'Flags'
        options:
          - value: ''
            name: '<none>'
            descriptions: 'Normal push'
            key: 'p'
          - value: '--force-with-lease'
            name: '--force-with-lease'
            description: "Only force over own commits"
            key: 'f'
