#:schema https://mise.en.dev/schema/mise.json

[settings]
npm.package_manager = "pnpm"

[tools]
bat = "latest"
dive = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
neovim = "latest"
node = "latest"
usage = "latest"
zoxide = "latest"
pnpm = "latest"
helix = "latest"
delta = "latest"
yazi = "latest"
bun = "latest"
"npm:vscode-json-languageserver" = "latest"
github-cli = "latest"
uv = "latest"
"npm:@openchamber/web" = "latest"
opencode = "latest"
"github:zed-industries/zed" = "latest"
watchexec = "latest"
