[tools]
bat = "latest"
dive = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
neovim = "latest"
node = "latest"
usage = "latest"
zoxide = "latest"
pnpm = "latest"
helix = "latest"
delta = "latest"
yazi = "latest"
"npm:opencode-ai" = "latest"
bun = "latest"
"npm:vscode-json-languageserver" = "latest"
github-cli = "latest"
uv = "latest"
